# Generated by Django 5.2.4 on 2025-07-04 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Спеціалізація', 'verbose_name_plural': 'Спеціалізації'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Профіль тренера', 'verbose_name_plural': 'Профілі тренерів'},
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Чоловік'), ('FEMALE', 'Жінка')], max_length=10, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('user', 'Користувач'), ('trainer', 'Тренер'), ('manager', 'Менеджер'), ('main manager', 'Головний менеджер')], default='user', max_length=20, verbose_name='Статус/роль'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, default='apps/core/static/img/avatar.png', upload_to='trainer_img/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text="Обов'язкове поле. Використовується для входу в систему.", max_length=254, unique=True, verbose_name='електронна пошта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контактний телефон'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Обліковий запис користувача'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Наприклад: Пн-Пт, 09:00-19:00', max_length=255, verbose_name='Час роботи'),
        ),
    ]
