# Generated by Django 5.2.4 on 2025-07-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_gender'),
        ('core', '0002_trainingtype_alter_traininghalls_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='core.trainingtype', verbose_name='Спеціалізації'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='working_hours',
            field=models.JSONField(blank=True, help_text="Наприклад: {'monday': {'open': '09:00', 'close': '19:00'}, 'saturday': {'open': '10:00', 'close': '16:00'}}", null=True, verbose_name='Робочі години'),
        ),
    ]
