# Generated by Django 5.2.4 on 2025-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_trainer_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='accounts.specialization', verbose_name='Спеціалізації'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='working_hours',
            field=models.JSONField(default={'friday': {'close': '20:00', 'open': '09:00'}, 'monday': {'close': '19:00', 'open': '09:00'}, 'saturday': {'close': '16:00', 'open': '10:00'}, 'sunday': None, 'thursday': {'close': '19:00', 'open': '09:00'}, 'tuesday': {'close': '19:00', 'open': '09:00'}, 'wednesday': {'close': '19:00', 'open': '09:00'}}, help_text='Стандартний графік роботи. Неділя - вихідний (null).', verbose_name='Робочі години'),
        ),
    ]
