# Generated by Django 5.2.4 on 2025-07-04 22:07

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_trainer_specializations_and_more'),
    ]


