# Generated by Django 5.2.4 on 2025-07-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_trainer_specializations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='working_hours',
        ),
    ]
