# Generated by Django 5.2.4 on 2025-07-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_trainer_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(choices=[('user', 'Користувач'), ('trainer', 'Тренер'), ('manager', 'Менеджер'), ('main manager', 'Головний менеджер')], default='trainer', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('user', 'Користувач'), ('trainer', 'Тренер'), ('manager', 'Менеджер'), ('main manager', 'Головний менеджер')], default='user', max_length=20, verbose_name='Статус'),
        ),
    ]
