# Generated by Django 5.2.4 on 2025-07-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_trainer_status_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='status',
            field=models.CharField(default='trainer', max_length=20, verbose_name='Статус'),
        ),
    ]
