# Generated by Django 5.2.4 on 2025-07-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_trainer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='status',
        ),
    ]
