# Generated by Django 5.2.4 on 2025-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_trainer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='accounts.specialization', verbose_name='Спеціалізації'),
        ),
    ]
