# Generated by Django 5.2.4 on 2025-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_trainer_specializations'),
        ('core', '0002_trainingtype_alter_traininghalls_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='core.trainingtype', verbose_name='Спеціалізації'),
        ),
    ]
