# Generated by Django 5.2.4 on 2025-07-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_trainer_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='about',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='Опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to='accounts.specialization', verbose_name='Обліковий запис користувача'),
        ),
    ]
