# Generated by Django 5.2.4 on 2025-07-04 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва тренування')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип тренування',
                'verbose_name_plural': 'Типи тренувань',
            },
        ),
        migrations.AlterModelOptions(
            name='traininghalls',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Зали'},
        ),
        migrations.RemoveField(
            model_name='traininghalls',
            name='hall_name',
        ),
        migrations.AddField(
            model_name='traininghalls',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Місткість'),
        ),
        migrations.AddField(
            model_name='traininghalls',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Назва залу'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.PositiveIntegerField(default=1, verbose_name='Макс. місткість')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Записано')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота'), (7, 'Неділя')], verbose_name='День тижня')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час закінчення')),
                ('status', models.CharField(choices=[('Started', 'Набір'), ('Full', 'Заповнено'), ('Ongoing', 'Триває'), ('Finished', 'Закінчилося')], default='Started', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_author', to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.traininghalls', verbose_name='Зал')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('training_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainingtype', verbose_name='Тренування')),
            ],
            options={
                'verbose_name': 'Запис у розкладі',
                'verbose_name_plural': 'Розклад',
                'unique_together': {('hall', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='Час запису')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.schedule', verbose_name='Тренування в розкладі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запис на тренування',
                'verbose_name_plural': 'Записи на тренування',
                'unique_together': {('user', 'schedule')},
            },
        ),
    ]
