# Generated by Django 5.2.4 on 2025-07-05 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainingtype_alter_traininghalls_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Started', 'Набір'), ('Full', 'Заповнено'), ('Ongoing', 'Триває'), ('Finished', 'Закінчилося'), ('Canceled', 'Скасовано')], default='Started', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
